# Generated by Django 4.2.7 on 2026-05-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='target_ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_requests', to='ward.ward'),
        ),
        migrations.AddField(
            model_name='bloodcamp',
            name='hospital',
            field=models.ForeignKey(limit_choices_to={'role': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='blood_camps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='donorbadge',
            unique_together={('donor', 'badge')},
        ),
        migrations.AlterUniqueTogether(
            name='donationresponse',
            unique_together={('request', 'donor')},
        ),
        migrations.AlterUniqueTogether(
            name='campregistration',
            unique_together={('camp', 'donor')},
        ),
    ]
