# Generated by Django 4.2.7 on 2026-06-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='bystander_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='donationresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('missed', 'Missed'), ('not_needed', 'Not Needed'), ('arrived_no_donation', 'Arrived No Donation'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
