# Generated by Django 4.2.7 on 2026-05-21 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.CharField(max_length=20)),
                ('local_body_name', models.CharField(max_length=255)),
                ('local_body_type', models.CharField(default='Gram Panchayat', help_text='Gram Panchayat / Municipality / Corporation', max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wards',
                'ordering': ['state', 'district', 'ward_number'],
                'unique_together': {('ward_number', 'local_body_name', 'state')},
            },
        ),
        migrations.CreateModel(
            name='WardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ward_member_profile', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ward.ward')),
            ],
            options={
                'db_table': 'ward_members',
            },
        ),
        migrations.CreateModel(
            name='WardBloodAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_condition', models.TextField(blank=True)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_phone', models.CharField(blank=True, max_length=20)),
                ('hospital_whatsapp', models.CharField(blank=True, max_length=20)),
                ('hospital_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hospital_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('hospital_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('notified', 'Notified'), ('resolved', 'Resolved')], default='pending', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ward_alerts', to='donation.bloodrequest')),
                ('ward_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_alerts', to='ward.wardmember')),
            ],
            options={
                'db_table': 'ward_blood_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardDonorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('not_available', 'Not Available'), ('donated', 'Donated')], default='pending', max_length=14)),
                ('notes', models.TextField(blank=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_notifications', to='ward.wardbloodalert')),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.CASCADE, related_name='ward_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ward_donor_notifications',
                'unique_together': {('alert', 'donor')},
            },
        ),
    ]
